// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.6
// source: pkg/snapshot/proto/v1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNumber        uint64         `protobuf:"varint,1,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	BlockHash          []byte         `protobuf:"bytes,2,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	StateRoot          []byte         `protobuf:"bytes,3,opt,name=StateRoot,proto3" json:"StateRoot,omitempty"`
	BlockchainSnapshot *KeyValuePairs `protobuf:"bytes,4,opt,name=blockchainSnapshot,proto3" json:"blockchainSnapshot,omitempty"`
	StateSnapshot      *KeyValuePairs `protobuf:"bytes,5,opt,name=stateSnapshot,proto3" json:"stateSnapshot,omitempty"`
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_snapshot_proto_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_snapshot_proto_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_pkg_snapshot_proto_v1_proto_rawDescGZIP(), []int{0}
}

func (x *StateSnapshot) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *StateSnapshot) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *StateSnapshot) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *StateSnapshot) GetBlockchainSnapshot() *KeyValuePairs {
	if x != nil {
		return x.BlockchainSnapshot
	}
	return nil
}

func (x *StateSnapshot) GetStateSnapshot() *KeyValuePairs {
	if x != nil {
		return x.StateSnapshot
	}
	return nil
}

type KeyValuePairs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys   [][]byte `protobuf:"bytes,1,rep,name=Keys,proto3" json:"Keys,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *KeyValuePairs) Reset() {
	*x = KeyValuePairs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_snapshot_proto_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValuePairs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePairs) ProtoMessage() {}

func (x *KeyValuePairs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_snapshot_proto_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePairs.ProtoReflect.Descriptor instead.
func (*KeyValuePairs) Descriptor() ([]byte, []int) {
	return file_pkg_snapshot_proto_v1_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValuePairs) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KeyValuePairs) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_pkg_snapshot_proto_v1_proto protoreflect.FileDescriptor

var file_pkg_snapshot_proto_v1_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76,
	0x31, 0x22, 0xe9, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f,
	0x74, 0x12, 0x41, 0x0a, 0x12, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x73,
	0x52, 0x12, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x12, 0x37, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x31,
	0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52, 0x0d,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x22, 0x3b, 0x0a,
	0x0d, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x4b, 0x65,
	0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x15, 0x5a, 0x13, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_snapshot_proto_v1_proto_rawDescOnce sync.Once
	file_pkg_snapshot_proto_v1_proto_rawDescData = file_pkg_snapshot_proto_v1_proto_rawDesc
)

func file_pkg_snapshot_proto_v1_proto_rawDescGZIP() []byte {
	file_pkg_snapshot_proto_v1_proto_rawDescOnce.Do(func() {
		file_pkg_snapshot_proto_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_snapshot_proto_v1_proto_rawDescData)
	})
	return file_pkg_snapshot_proto_v1_proto_rawDescData
}

var file_pkg_snapshot_proto_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_snapshot_proto_v1_proto_goTypes = []interface{}{
	(*StateSnapshot)(nil), // 0: v1.StateSnapshot
	(*KeyValuePairs)(nil), // 1: v1.KeyValuePairs
}
var file_pkg_snapshot_proto_v1_proto_depIdxs = []int32{
	1, // 0: v1.StateSnapshot.blockchainSnapshot:type_name -> v1.KeyValuePairs
	1, // 1: v1.StateSnapshot.stateSnapshot:type_name -> v1.KeyValuePairs
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_snapshot_proto_v1_proto_init() }
func file_pkg_snapshot_proto_v1_proto_init() {
	if File_pkg_snapshot_proto_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_snapshot_proto_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_snapshot_proto_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValuePairs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_snapshot_proto_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_snapshot_proto_v1_proto_goTypes,
		DependencyIndexes: file_pkg_snapshot_proto_v1_proto_depIdxs,
		MessageInfos:      file_pkg_snapshot_proto_v1_proto_msgTypes,
	}.Build()
	File_pkg_snapshot_proto_v1_proto = out.File
	file_pkg_snapshot_proto_v1_proto_rawDesc = nil
	file_pkg_snapshot_proto_v1_proto_goTypes = nil
	file_pkg_snapshot_proto_v1_proto_depIdxs = nil
}
